 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/data_points", type: :request do
  
  # DataPoint. As you add validations to DataPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DataPoint.create! valid_attributes
      get data_points_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      data_point = DataPoint.create! valid_attributes
      get data_point_url(data_point)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_data_point_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      data_point = DataPoint.create! valid_attributes
      get edit_data_point_url(data_point)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DataPoint" do
        expect {
          post data_points_url, params: { data_point: valid_attributes }
        }.to change(DataPoint, :count).by(1)
      end

      it "redirects to the created data_point" do
        post data_points_url, params: { data_point: valid_attributes }
        expect(response).to redirect_to(data_point_url(DataPoint.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DataPoint" do
        expect {
          post data_points_url, params: { data_point: invalid_attributes }
        }.to change(DataPoint, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post data_points_url, params: { data_point: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested data_point" do
        data_point = DataPoint.create! valid_attributes
        patch data_point_url(data_point), params: { data_point: new_attributes }
        data_point.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the data_point" do
        data_point = DataPoint.create! valid_attributes
        patch data_point_url(data_point), params: { data_point: new_attributes }
        data_point.reload
        expect(response).to redirect_to(data_point_url(data_point))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        data_point = DataPoint.create! valid_attributes
        patch data_point_url(data_point), params: { data_point: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested data_point" do
      data_point = DataPoint.create! valid_attributes
      expect {
        delete data_point_url(data_point)
      }.to change(DataPoint, :count).by(-1)
    end

    it "redirects to the data_points list" do
      data_point = DataPoint.create! valid_attributes
      delete data_point_url(data_point)
      expect(response).to redirect_to(data_points_url)
    end
  end
end
